/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface UserMenu {
    /**
    * Menu link
    */
    'menu_links': string;
    /**
    * Profile picture
    */
    'profile_picture': string;
  }
  interface UserMenuContainer {}
}

declare global {


  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLUserMenuElement extends Components.UserMenu, HTMLStencilElement {}
  var HTMLUserMenuElement: {
    prototype: HTMLUserMenuElement;
    new (): HTMLUserMenuElement;
  };

  interface HTMLUserMenuContainerElement extends Components.UserMenuContainer, HTMLStencilElement {}
  var HTMLUserMenuContainerElement: {
    prototype: HTMLUserMenuContainerElement;
    new (): HTMLUserMenuContainerElement;
  };
  interface HTMLElementTagNameMap {
    'my-component': HTMLMyComponentElement;
    'user-menu': HTMLUserMenuElement;
    'user-menu-container': HTMLUserMenuContainerElement;
  }
}

declare namespace LocalJSX {
  interface MyComponent {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }
  interface UserMenu {
    /**
    * Menu link
    */
    'menu_links'?: string;
    /**
    * Profile picture
    */
    'profile_picture'?: string;
  }
  interface UserMenuContainer {}

  interface IntrinsicElements {
    'my-component': MyComponent;
    'user-menu': UserMenu;
    'user-menu-container': UserMenuContainer;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'my-component': LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
      'user-menu': LocalJSX.UserMenu & JSXBase.HTMLAttributes<HTMLUserMenuElement>;
      'user-menu-container': LocalJSX.UserMenuContainer & JSXBase.HTMLAttributes<HTMLUserMenuContainerElement>;
    }
  }
}


